# ============================================
# GW-EAF API Documentation Generator
# ============================================

$OutputFile = Join-Path $PSScriptRoot "GW-EAF-API-Reference.md"

# Import module
Import-Module "$PSScriptRoot\..\Modules\Repository.Common.psm1" -Force

# Get all functions
$Functions = Get-Command -Module Repository.Common | Sort-Object Name

# Build the documentation
$Content = @"
# GW-EAF API Reference

## Overview

The Golden Wings Enterprise Automation Framework (GW-EAF) provides **$($Functions.Count)** exported functions organized into **10 services**.

## Service Index

| Service | Functions | Description |
|---------|-----------|-------------|
| Configuration | 7 | Repository configuration |
| Logging | 8 | Structured logging |
| Orchestration | 1 | Build orchestration |
| Utilities | 4 | File/path utilities |
| Timing | 2 | Build timing |
| Statistics | 1 | Repository statistics |
| Release | 2 | Release helpers |
| Repository | 4 | Repository discovery |
| Document | 4 | Document metadata |
| Validation | 3 | Validation framework |
| Hash | 3 | Hash generation |
| Manifest | 3 | Manifest generation |
| Evidence | 3 | Evidence management |
| Report | 3 | Report generation |
| Git | 7 | Git operations |
| **Total** | **$($Functions.Count)** | |

---

## Function Reference

"@

foreach ($Function in $Functions) {
    $Content += @"

### $($Function.Name)

**Category:** $(($Function.Source).Split('\')[-1])

**Syntax:**
```powershell
$(($Function.Definition -replace "`n", "`n    "))
"@
}

$Content += @"

---

## Version Information

| Property | Value |
|----------|-------|
| **Version** | 1.9.0 |
| **Baseline** | GW-BASELINE-2026.1 |
| **Git Tag** | Repository.Common-v1.9.0 |
| **Total Functions** | $($Functions.Count) |

---

*Generated by GW-EAF API Documentation Generator*
"@

# Write to file
$Content | Set-Content -Path $OutputFile -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "API Documentation Generated" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Output: $OutputFile"
Write-Host "Functions: $($Functions.Count)"
Write-Host ""